### ISSUE TITLE
Restore test coverage

### ISSUE THREAD

**Issue by xurizaemon** [hubot-friends/botforge#45]
Previously hubotio/hubot used Travis. Planning to use Github Actions here instead.

- [x] npm test to run tests
- [x] Review warnings from npm run test (see output in actions)
- [x] npm audit to show updates required (which will complain a lot)
- [x] e2e testing (test generation of a hubot via hubot-generator - ref https://github.com/hubotio/hubot/issues/1063)
- [x] Cross-OS test coverage

**Comment by xurizaemon** [comment]
Before I manually add `npm audit` here, I figured I'd try [Github's built-in scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository). If that's not the right thing for us, we can swap to an Action based workflow or something else.

**Comment by xurizaemon** [comment]
Oh gosh Dependabot is gonna open a few PRs here I think 🤣

**Comment by joeyguerra** [comment]
I'm literally watching it right now in Actions.

**Comment by xurizaemon** [comment]
@joeyguerra likewise! Love that several passed and one failed - tests 🪄 

Feel free to merge any / all you have confidence in.

**Comment by joeyguerra** [comment]
@xurizaemon are you saying I can merge the PRs I opened?

**Comment by joeyguerra** [comment]
ah, I see. Dependabot opened some PRs. are you reviewing those PRs too? I don't want to step on each other's toes. We should get chat for faster feedback :)

**Comment by xurizaemon** [comment]
Not reviewing them, I'm sanding some shelves :D

**Comment by joeyguerra** [comment]
Cool. I'm reviewing the most recent failed PR. Looks like it failed because it failed a bunch of standard rules.

**Comment by joeyguerra** [comment]
I've merged all the dendebot PRs as of 12:31 AM CST. I there's more, it must've created them after that.

**Comment by xurizaemon** [comment]
Actually was kinda nice to have Standard JS kick in and correct a missing blank line in my test changes 😁 it's good when it's tidy!

**Comment by joeyguerra** [comment]
I'd like to get away from using yeoman.

**Comment by joeyguerra** [comment]
Closing this. I'm fixing the e2e test as part of the effort to not use yeoman anymore.

https://github.com/hubotio/hubot/pull/1644
